### ISSUE TITLE
Can you please create a step-by-step firmware building and downloading?

### ISSUE THREAD

**Issue by toneytang** [RudolphRiedel/USB_CAN-FD#1]
Thank .

**Comment by RudolphRrr** [comment]
Oh? Only saw this by chance, I have not seen a notification for this issue.

This repository does not have any frmware as this is a collaboration, check out: https://github.com/jgressmann/supercan

Downloading the firmware depends on the variant, for ATSAME51 I open Microchip Studio and flash the Supercan bootloader with either an Atmel ICE or a Segger JLink.
With the STM32G0B1 variant the firmware is just flashed with DFU-Util as the STM32 already has an USB bootloader built in.

**Comment by zerotoney** [comment]
Thank you. I will give it a try. Still frustrated where to get the whole firmware project. New guy to STM.

**Comment by toneytang** [comment]
https://github.com/jgressmann/tinyusb/tree/master/examples/device/supercan
